import "./globals.css";
import type { Metadata } from "next";

import Sidebar from "./components/Sidebar";
import Providers from "./providers";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className="bg-grayLight flex justify-between border-2">
                <Providers>
                    <Sidebar />
                    {children}
                </Providers>
            </body>
        </html>
    );
}
