import type { Metadata } from "next";
import Header from "../components/Header";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    return (
        <div className="flex flex-col my-[30px] mr-[30px] gap-[10px]">
            <Header />
            {children}
        </div>
    );
}
